#!/usr/bin/env node
/**
 * gen-worker.mjs -- write deploy/worker-words.js from the canonical lists in
 * src/words.mjs, so the Cloudflare Worker and the Node server never drift.
 *
 *   npm run gen:worker
 *
 * Run it after editing src/words.mjs; commit the regenerated file.
 */

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { ADJECTIVES, NOUNS } from "../src/words.mjs";

const out = fileURLToPath(new URL("../deploy/worker-words.js", import.meta.url));

const fmt = (list) =>
  list
    .map((w, i) => (i % 10 === 0 ? "\n  " : "") + JSON.stringify(w) + ",")
    .join("")
    .replace(/,$/, "");

writeFileSync(
  out,
  `// GENERATED by scripts/gen-worker.mjs from src/words.mjs -- do not edit by hand.\n` +
    `export const ADJECTIVES = [${fmt(ADJECTIVES)}\n];\n\n` +
    `export const NOUNS = [${fmt(NOUNS)}\n];\n`,
);

console.log(`wrote deploy/worker-words.js  (${ADJECTIVES.length} adjectives, ${NOUNS.length} nouns)`);
